//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_admin
    {
        public int id_contact { get; set; }
        public string nom_contact { get; set; }
        public string prenom_contact { get; set; }
        public string email_contact { get; set; }
        public string sujet_contact { get; set; }
        public string Contenu { get; set; }
        public int id_admin { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
