//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employeur()
        {
            this.Avis = new HashSet<Avi>();
            this.Fichiers = new HashSet<Fichier>();
            this.Heure_travail = new HashSet<Heure_travail>();
            this.Messages = new HashSet<Message>();
            this.Notes = new HashSet<Note>();
            this.Reclamations = new HashSet<Reclamation>();
            this.Rendez_vous = new HashSet<Rendez_vous>();
        }
        


        public int id_employeur { get; set; }
        public string nom_employeur { get; set; }
        public string prenom_employeur { get; set; }
        public string photo_employeur { get; set; }
        public string email_employeur { get; set; }
        public string sexe_employeur { get; set; }
        public string mobile_employeur { get; set; }
        public string ville { get; set; }
        public string adresse { get; set; }
        public bool disponibilité_emp { get; set; }
        public string password_employeur { get; set; }
        public string titre_serv_emp { get; set; }
        public string desc_serv_emp { get; set; }
        public double prix { get; set; }
        public int id_service { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avi> Avis { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fichier> Fichiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Heure_travail> Heure_travail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamation> Reclamations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendez_vous> Rendez_vous { get; set; }
    }
}
