//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichier
    {
        public int id_fichier { get; set; }
        public string nom_fichier { get; set; }
        public string fichier1 { get; set; }
        public int id_employeur { get; set; }
    
        public virtual Employeur Employeur { get; set; }
    }
}
