//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heure_travail
    {
        public int id_heure { get; set; }
        public System.TimeSpan heure_debut { get; set; }
        public System.TimeSpan heure_fin { get; set; }
        public int id_jour { get; set; }
        public int id_employeur { get; set; }
    
        public virtual Employeur Employeur { get; set; }
        public virtual Jour Jour { get; set; }
    }
}
