//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonneServiceEntities : DbContext
    {
        public PersonneServiceEntities()
            : base("name=PersonneServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Avi> Avis { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contact_admin> Contact_admin { get; set; }
        public virtual DbSet<Employeur> Employeurs { get; set; }
        public virtual DbSet<Fichier> Fichiers { get; set; }
        public virtual DbSet<Heure_travail> Heure_travail { get; set; }
        public virtual DbSet<Historique_client> Historique_client { get; set; }
        public virtual DbSet<Jour> Jours { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Reclamation> Reclamations { get; set; }
        public virtual DbSet<Rendez_vous> Rendez_vous { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Type_note> Type_note { get; set; }
    }
}
