//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServicePersonne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendez_vous
    {
        public int id_employeur { get; set; }
        public int id_client { get; set; }
        public System.DateTime date_RDV { get; set; }
        public System.TimeSpan heure_RDV { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employeur Employeur { get; set; }
    }
}
